In [1]:
#!/usr/bin/env python3

import rospy

from time import sleep

from client_arm import ArmClient
from client_base import BaseClient
from client_gripper import RobotiqGripper
import geometry_msgs.msg as geometry_msgs

import numpy as np


In [2]:
rospy.init_node('happy_arm_jupyter')
sleep(1)
base = BaseClient()
arm = ArmClient()
gripper = RobotiqGripper("192.168.50.82")

Connecting to gripper...
Activating gripper...
Gripper auto-calibrated to [3, 227]


In [3]:
from tf.transformations import quaternion_from_euler
def angle_deg(rx,ry,rz):
    return quaternion_from_euler(rx*np.pi/180,ry*np.pi/180,rz*np.pi/180)

header: 
  seq: 0
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: "map"
pose: 
  position: 
    x: 16.33
    y: 22.378
    z: 0.0
  orientation: 
    x: 0.0
    y: 0.0
    z: 0.8509035245341184
    w: 0.5253219888177297


In [7]:
#

#RPY = 0 0 0  <<>> 0,0,0,1
# 0 0 90 <<>> 0, 0, 0.7071068, 0.7071068
#0 90 0 <<>> 0, 0.7071068, 0, 0.7071068
#90 0 0 <<>>  0.7071068, 0, 0, 0.7071068
#90 90 0 <<>> 0.6335811, 0.6335811, 0, 0.4440158

q = angle_deg(0,0,0)
print(q)

pose_list = [
    geometry_msgs.Pose(
        geometry_msgs.Vector3(0.2, -.3, -0.05), geometry_msgs.Quaternion( 0, 0, 0, 1 )
    ),
]
duration_list = [20.0]


arm.move(pose_list, duration_list)

[0. 0. 0. 1.]
[INFO] [1633108143.367227]: Executing trajectory using the pose_based_cartesian_traj_controller


KeyboardInterrupt: 

In [4]:
# base.move(16.3, 25.5, 90.0)
# gripper.move_and_wait_for_pos(120,100,100)

(120, <ObjectStatus.AT_DEST: 3>)

In [14]:
jp = np.array([-2.3432838916778564, -1.5725609264769496, -0.0008013884173792007, -0.7542601388743897, -1.5583012739764612, -1.6505096594439905])
print(np.round(jp*180/np.pi))

[-134.  -90.   -0.  -43.  -89.  -95.]


In [34]:
from tf.transformations import quaternion_from_euler
import numpy as np

def angle_rad(rx,ry,rz):
    return quaternion_from_euler(rx,ry,rz)

print(angle_rad(1.209*2,1.209*2,-1.209*2))

[ 0.42678341 -0.1924365  -0.42678341 -0.77374417]


In [32]:
def angle_deg(rx,ry,rz):
    return quaternion_from_euler(rx*np.pi/180,ry*np.pi/180,rz*np.pi/180)
angle_deg(90,90,0)

array([ 0.5,  0.5, -0.5,  0.5])

In [35]:
import tf

In [41]:
dir(geometry_msgs.Quaternion)

['__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 '_check_types',
 '_connection_header',
 '_full_text',
 '_get_types',
 '_has_header',
 '_md5sum',
 '_slot_types',
 '_type',
 'deserialize',
 'deserialize_numpy',
 'serialize',
 'serialize_numpy',
 'w',
 'x',
 'y',
 'z']

In [39]:
from tf import Quaternion

ImportError: cannot import name 'Quaternion' from 'tf' (/opt/ros/noetic/lib/python3/dist-packages/tf/__init__.py)