In [1]:
#!/usr/bin/env python3

import rospy

from time import sleep

from client_arm import ArmClient
from client_base import BaseClient
from client_gripper import RobotiqGripper
import geometry_msgs.msg as geometry_msgs

import numpy as np


In [2]:
rospy.init_node('happy_arm_jupyter')
sleep(1)
base = BaseClient()
arm = ArmClient()
gripper = RobotiqGripper("192.168.50.82")

Connecting to gripper...
Activating gripper...
Gripper auto-calibrated to [3, 227]


In [3]:
from tf.transformations import quaternion_from_euler
def angle_deg(rx,ry,rz):
    return quaternion_from_euler(rx*np.pi/180,ry*np.pi/180,rz*np.pi/180)

header: 
  seq: 0
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: "map"
pose: 
  position: 
    x: 16.33
    y: 22.378
    z: 0.0
  orientation: 
    x: 0.0
    y: 0.0
    z: 0.8509035245341184
    w: 0.5253219888177297


In [7]:
#

#RPY = 0 0 0  <<>> 0,0,0,1
# 0 0 90 <<>> 0, 0, 0.7071068, 0.7071068
#0 90 0 <<>> 0, 0.7071068, 0, 0.7071068
#90 0 0 <<>>  0.7071068, 0, 0, 0.7071068
#90 90 0 <<>> 0.6335811, 0.6335811, 0, 0.4440158

q = angle_deg(0,0,0)
print(q)

pose_list = [
    geometry_msgs.Pose(
        geometry_msgs.Vector3(0.2, -.3, -0.05), geometry_msgs.Quaternion( 0, 0, 0, 1 )
    ),
]
duration_list = [20.0]


arm.move(pose_list, duration_list)

[0. 0. 0. 1.]
[INFO] [1633108143.367227]: Executing trajectory using the pose_based_cartesian_traj_controller


KeyboardInterrupt: 

In [4]:
# base.move(16.3, 25.5, 90.0)
# gripper.move_and_wait_for_pos(120,100,100)

(120, <ObjectStatus.AT_DEST: 3>)

In [14]:
jp = np.array([-2.3432838916778564, -1.5725609264769496, -0.0008013884173792007, -0.7542601388743897, -1.5583012739764612, -1.6505096594439905])
print(np.round(jp*180/np.pi))

[-134.  -90.   -0.  -43.  -89.  -95.]


In [27]:
from tf.transformations import quaternion_from_euler
import numpy as np

def angle_rad(rx,ry,rz):
    return quaternion_from_euler(rx,ry,rz)

In [28]:
print(angle_rad(1.209,1.209,-1.209))

[-0.65053921  0.11898205  0.65053921  0.37341767]
